'use strict';
const $=id=>document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d');
const people=[{name:'Bogle Fund 2',detail:'The quiet contender',img:'gallery-plate-02.png'},{name:'Bogle Fund 1',detail:'Quick. Unpredictable.',img:'gallery-plate-07.png'},{name:'Midas Fund',detail:'Clockwork reflexes',img:'gallery-plate-04.png'},{name:'Smaug Fund',detail:'The reigning champion',img:'gallery-plate-08.png'}];
const portraits=people.map(p=>{const i=new Image();i.src='assets/'+p.img;return i});
let room=new Image();room.src='assets/room.png';let atlas=new Image();atlas.src='assets/sprites.png';let sprites=null;
atlas.onload=()=>{const source=document.createElement('canvas');source.width=atlas.width;source.height=atlas.height;const sc=source.getContext('2d',{willReadFrequently:true});sc.drawImage(atlas,0,0);const pixels=sc.getImageData(0,0,source.width,source.height);for(let i=0;i<pixels.data.length;i+=4){let r=pixels.data[i],g=pixels.data[i+1],b=pixels.data[i+2];if(g>90&&g>r*1.4&&g>b*1.4)pixels.data[i+3]=0}sc.putImageData(pixels,0,0);sprites=[0,1,2].map((row)=>people.map((p,col)=>{const out=document.createElement('canvas');out.width=row===2?42:36;out.height=row===2?64:86;const oc=out.getContext('2d');oc.imageSmoothingEnabled=false;const boxes=[[24,42,214,529],[24,620,214,494],[25,1165,214,319]];const [x,y,w,h]=boxes[row];oc.drawImage(source,(col*256+x)*atlas.width/1024,y*atlas.height/1536,w*atlas.width/1024,h*atlas.height/1536,0,0,out.width,out.height);return out}));};
let state={phase:'idle',round:1,active:[0,1,2,3],chairs:[],seated:{},angle:0,phaseAt:0,redAt:0,greenFor:0,bots:[],lastReaction:null,loser:null,paused:false,pauseAt:0,finishAt:0};
let lastFrame=performance.now(),clock=lastFrame,sound=false,audioCtx=null,lastBeat=0,note=0;
const melody=[261.63,329.63,392,329.63,293.66,349.23,440,349.23,261.63,329.63,392,523.25,440,392,349.23,293.66];
function tone(freq,duration=.12,type='square',volume=.035){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{}}
function roster(){ $('roster').innerHTML=people.map((p,i)=>`<div class="person ${state.active.includes(i)?'':'out'}"><img src="assets/${p.img}" alt="${p.name}"><div><strong>${p.name}</strong><small>${state.active.includes(i)?(i===0?'Your character':p.detail):'Eliminated'}</small></div>${i===0?'<span class="tag">YOU</span>':''}</div>`).join('');document.querySelector('.aside-title>span').textContent=String(state.active.length).padStart(2,'0')}
function signal(kind,text){$('signal').className='signal '+kind;$('signal').lastElementChild.textContent=text}
function setHint(t){$('hint').textContent=t}
function hideOverlays(){['intro','result','pause-overlay'].forEach(id=>$(id).classList.add('hidden'))}
function layoutChairs(){const n=state.active.length-1;state.chairs=Array.from({length:n},(_,i)=>({x:480+(i-(n-1)/2)*110,y:417}));}
function begin(){hideOverlays();state={...state,phase:'countdown',round:1,active:[0,1,2,3],angle:0,lastReaction:null,paused:false};$('reaction').innerHTML='— <small>ms</small>';startRound()}
function startRound(){hideOverlays();state.phase='countdown';state.phaseAt=performance.now();state.seated={};state.moves={};state.loser=null;state.bots=[];state.finishAt=0;state.greenFor=3200+Math.random()*4700;layoutChairs();$('round').textContent=`ROUND 0${state.round} / 03`;$('chairs').textContent=`${state.active.length} GUESTS · ${state.chairs.length} CHAIRS`;$('sit').disabled=true;$('pause').disabled=false;signal('','GET READY');setHint('Three, two, one… Watch the light.');roster()}
function goGreen(now){state.phase='green';state.phaseAt=now;signal('green','KEEP WALKING');$('sit').disabled=false;$('countdown').classList.add('hidden');setHint('Hold your nerve. Wait for red.');lastBeat=0;}
// Each rival reacts independently; later rounds are faster, never before red.
const rivalProfiles = {1:{base:245,spread:230},2:{base:265,spread:120},3:{base:233,spread:190}};
function rivalDelay(id,round,rng=Math.random){
  const p=rivalProfiles[id];
  const reaction=p.base+(rng()+rng())*.5*p.spread-(round-1)*14;
  return Math.round(Math.max(190,reaction+(rng()<.08?70:0)));
}
function goRed(now){state.phase='red';state.phaseAt=now;state.redAt=now;state.bots=state.active.filter(i=>i!==0).map(id=>({id,at:now+rivalDelay(id,state.round)})).sort((a,b)=>a.at-b.at);signal('red','SIT NOW!');setHint('Now! Press SPACE or tap SIT.');tone(160,.25,'sawtooth',.05);canvas.classList.remove('flash');void canvas.offsetWidth;canvas.classList.add('flash')}
function position(id){const idx=state.active.indexOf(id),a=state.angle+idx*Math.PI*2/state.active.length;return{x:480+Math.cos(a)*282,y:421+Math.sin(a)*101,a}}
function claim(id){if(state.seated[id]!==undefined)return false;const taken=Object.values(state.seated),free=state.chairs.map((c,i)=>i).filter(i=>!taken.includes(i));if(!free.length)return false;const p=position(id);free.sort((a,b)=>Math.hypot(state.chairs[a].x-p.x,state.chairs[a].y-p.y)-Math.hypot(state.chairs[b].x-p.x,state.chairs[b].y-p.y));state.moves??={};state.moves[id]={from:p,at:performance.now()};state.seated[id]=free[0];if(id===0){$('sit').disabled=true;setHint('Seat secured!');tone(660,.12);setTimeout(()=>tone(880,.16),110)}if(Object.keys(state.seated).length===state.chairs.length){state.loser=state.active.find(i=>state.seated[i]===undefined);state.phase='resolving';state.finishAt=performance.now()+1000;$('sit').disabled=true;$('pause').disabled=true;}return true}
function sit(){if(state.paused)return;if(state.phase==='green'){state.loser=0;state.phase='resolving';state.finishAt=performance.now()+600;state.active.filter(i=>i!==0).forEach((id,i)=>state.seated[id]=i);$('sit').disabled=true;$('pause').disabled=true;setHint('Too soon! The light was still green.');signal('red','FALSE START');tone(110,.4,'sawtooth');state.early=true;return}if(state.phase!=='red')return;const now=performance.now();for(const b of state.bots)if(b.at<=now&&state.seated[b.id]===undefined&&state.phase==='red')claim(b.id);if(state.phase!=='red')return;state.lastReaction=Math.round(now-state.redAt);$('reaction').innerHTML=state.lastReaction+' <small>ms</small>';claim(0)}
function finish(){const eliminated=state.loser;state.active=state.active.filter(i=>i!==eliminated);roster();$('pause').disabled=true;$('countdown').classList.add('hidden');const lost=eliminated===0,won=!lost&&state.active.length===1;state.phase=lost?'lost':won?'won':'between';$('result-kicker').textContent=lost?'BETTER LUCK NEXT TIME':won?'THE LAST ONE SEATED':'ROUND COMPLETE';$('result-title').textContent=lost?(state.early?'TOO SOON.':'LEFT STANDING.'):(won?'THE LAST CHAIR IS YOURS!':'SEAT SECURED.');$('result-body').textContent=lost?(state.early?'You sat down on green. Wait for the red light before making your move.':'Your rivals took every seat. They came prepared. Try again.'):(won?`Three rounds. Three perfect moves. ${people[0].name} leaves the room a champion.`:`${people[eliminated].name} is out. Next up: ${state.active.length} guests, ${state.active.length-1} chairs.`);$('next').innerHTML=state.phase==='between'?'NEXT ROUND <span>↗</span>':'PLAY AGAIN <span>↻</span>';$('result').classList.remove('hidden');signal('',won?'YOU WIN':lost?'GAME OVER':'ONE LESS CHAIR');state.early=false;if(won){[523,659,784,1047].forEach((f,i)=>setTimeout(()=>tone(f,.25),i*140))}else if(lost)tone(140,.4);}
function pause(){if(!['countdown','green','red'].includes(state.phase)||state.paused)return;state.paused=true;state.pauseAt=performance.now();$('pause-overlay').classList.remove('hidden');$('pause').setAttribute('aria-label','Resume game')}
function resume(){if(!state.paused)return;const diff=performance.now()-state.pauseAt;state.phaseAt+=diff;state.redAt+=diff;state.bots.forEach(b=>b.at+=diff);Object.values(state.moves||{}).forEach(m=>m.at+=diff);state.paused=false;$('pause-overlay').classList.add('hidden');$('pause').setAttribute('aria-label','Pause game')}
function drawSprite(id,row,x,y,height){if(sprites){const sp=sprites[row][id],w=height*sp.width/sp.height;ctx.drawImage(sp,Math.round(x-w/2),Math.round(y-height),Math.round(w),height)}else if(portraits[id].complete){ctx.drawImage(portraits[id],x-45,y-90,90,90)}}
function draw(now){ctx.imageSmoothingEnabled=false;if(room.complete&&room.naturalWidth)ctx.drawImage(room,0,0,960,600);else{ctx.fillStyle='#a7b694';ctx.fillRect(0,0,960,600)}const items=[];const displayActive=state.phase==='idle'?[0,1,2,3]:[...new Set([...state.active,...Object.keys(state.seated).map(Number),...(state.loser===null?[]:[state.loser])])];state.chairs.forEach((ch,i)=>items.push({y:ch.y,draw:()=>{if(sprites)drawSprite(i%4,2,ch.x,ch.y,150);const occupant=Object.keys(state.seated).find(k=>state.seated[k]===i);if(occupant!==undefined){const move=state.moves?.[occupant];const t=move?Math.min(1,Math.max(0,(now-move.at)/160)):1;const ease=1-Math.pow(1-t,3);const x=move?move.from.x+(ch.x-move.from.x)*ease:ch.x;const y=move?move.from.y+(ch.y-2-move.from.y)*ease:ch.y-2;drawSprite(+occupant,t<.8?0:1,x,y,t<.8?188:180);label(+occupant,x,y+19)}}}));displayActive.forEach(id=>{if(state.seated[id]!==undefined)return;let p=state.active.includes(id)?position(id):{x:810,y:455,a:0};const moving=['idle','green'].includes(state.phase),bob=moving?Math.abs(Math.sin(now/125+id))*5:0;items.push({y:p.y,draw:()=>{ctx.fillStyle='#2f241c35';ctx.beginPath();ctx.ellipse(p.x,p.y+1,26,8,0,0,Math.PI*2);ctx.fill();drawSprite(id,0,p.x,p.y-bob,188);label(id,p.x,p.y+21)}})});items.sort((a,b)=>a.y-b.y).forEach(i=>i.draw());if(state.phase==='red'){ctx.strokeStyle='#a53532';ctx.lineWidth=8;ctx.strokeRect(4,4,952,592)}}
function label(id,x,y){if(id!==0)return;ctx.font='bold 14px monospace';ctx.textAlign='center';ctx.fillStyle='#2d4534';ctx.fillRect(x-22,y-12,44,19);ctx.fillStyle='#f0e8ca';ctx.fillText('YOU',x,y+2)}
function tick(now){const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;clock=now;if(!state.paused){if(state.phase==='idle'||state.phase==='green')state.angle+=dt*(state.phase==='idle'?.14:.68+state.round*.1);if(state.phase==='countdown'){let elapsed=now-state.phaseAt;$('countdown').classList.remove('hidden');$('countdown').textContent=Math.max(1,3-Math.floor(elapsed/850));if(elapsed>=2550)goGreen(now)}if(state.phase==='green'){if(now-lastBeat>310){tone(melody[note++%melody.length],.11,'triangle',.08);lastBeat=now}if(now-state.phaseAt>=state.greenFor)goRed(now)}if(state.phase==='red'){for(const b of state.bots){if(now>=b.at&&state.phase==='red')claim(b.id)}if(now-state.redAt>2200&&state.phase==='red'){state.loser=state.active.find(i=>state.seated[i]===undefined)??0;state.phase='resolving';state.finishAt=now+600;}}if(state.phase==='resolving'&&now>=state.finishAt)finish();}draw(state.paused?state.pauseAt:now);requestAnimationFrame(tick)}
$('start').onclick=begin;$('sit').addEventListener('pointerdown',e=>{e.preventDefault();sit()});$('sit').addEventListener('click',e=>{if(e.detail===0)sit()});$('next').onclick=()=>{if(state.phase==='between'){state.round++;startRound()}else begin()};$('pause').onclick=()=>state.paused?resume():pause();$('resume').onclick=resume;$('sound').onclick=()=>{sound=!sound;$('sound').textContent='SOUND: '+(sound?'ON':'OFF');$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Disable sound':'Enable sound');if(sound)tone(440)};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat){if(!['green','red'].includes(state.phase))return;e.preventDefault();sit()}if(e.code==='Escape'){state.paused?resume():pause()}});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
layoutChairs();roster();requestAnimationFrame(tick);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const tools=[{name:'read_game_state',description:'Read current round, light, remaining players and game status.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>({phase:state.phase,round:state.round,paused:state.paused,players:state.active.map(i=>people[i].name),reaction:state.lastReaction})},{name:'start_game',description:'Start a new musical chairs game, only when the current game is not running.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:(input)=>{if(input&&Object.keys(input).length)throw new Error('No arguments accepted');if(!['idle','won','lost'].includes(state.phase))throw new Error('A game is already active');begin();return{phase:state.phase,round:state.round}}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
